import useSWRImmutable from "swr/immutable";

function useApplyLists() {
  return {
    links: {
      prev_uri: "https://www.naver.com",
      next_uri: "https://www.naver.com",
    },
    data: {
      user: [
        {
          id: 1,
          name: "홍길동",
          major: "정보통신공학과",
          email: "mju@email.com",
          status: "지원완료",
          part: "기획",
        },
        {
          id: 2,
          name: "김철수",
          major: "정보통신공학과",
          email: "mjuackr@email.com",
          status: "서류탈락",
          part: "개발",
        },
        {
          id: 3,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 4,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 5,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 6,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 7,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 8,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 9,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 10,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 11,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 12,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 13,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 14,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 15,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 16,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 17,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 18,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 19,
          name: "명지대",
          major: "컴퓨터공학과123132",
          email: "abc4443d@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 20,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 21,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 22,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 23,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 24,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 25,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 26,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 27,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 28,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 29,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
        {
          id: 30,
          name: "테스트",
          major: "컴퓨터공학과",
          email: "abcd@email.com",
          status: "최종합격",
          part: "개발",
        },
      ],
    },
  };
}

export default useApplyLists;
